[package]
authors = ["patrick.fernie@gmail.com"]
description = "Implementation of Cookie storage and retrieval"
name = "cookie_store"
version = "0.11.0"
edition = "2018"
repository = "https://github.com/pfernie/cookie_store"
documentation = "https://docs.rs/cookie_store"
readme = "README.md"
license = "MIT/Apache-2.0"

[features]
default = ["reqwest_impl"]

# uses `indexmap::IndexMap` in lieu of HashMap internally, so cookies are maintained in insertion/creation order
preserve_order = ["indexmap"]
# provide an implementation of `reqwest::cookie::CookieStorage`
reqwest_impl = ["reqwest"]

[dependencies]
idna = "0.2.0"
log = "0.4.8"
publicsuffix = { version = "1.5.4", default-features = false }
serde = { version = "1.0.111", features = [ "derive" ] }
serde_json = "1.0.55"
time = "0.2.16"
url = "2.1.1"

indexmap = { version = "1.4.0", optional = true }
# reqwest = { version = "^0.10.9", optional = true }
reqwest = { git = "https://github.com/pfernie/reqwest", branch="cookie-storage", optional = true, features = ["cookies"] }

[dependencies.cookie]
features = ["percent-encode"]
version = "0.14.1"

[dev-dependencies]
env_logger = "0.7.1"
pretty_assertions = "0.6.1"
